language: node_js
dist: trusty
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm test
  - npm run lint
after_success:
  - npm run semantic-release
  - npx nyc report --reporter=text-lcov | npx coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
